# Generated by Django 5.1.7 on 2025-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeneedscare'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeneedscare',
            name='needs_attention',
            field=models.BooleanField(default=False),
        ),
    ]
